version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
      - "9092:9092"
      - "2181:2181"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./ElasticAgent:/usr/share/elasticsearch/ElasticAgent
    #  - ./Elastic/bin:/usr/share/elasticsearch/bin
    environment:
      - ELASTIC_USERNAME=admin
      - ELASTIC_PASSWORD=admin
  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.0
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - KIBANA_ELASTICSEARCH_URL=elasticsearch
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
      - ELASTIC_USERNAME=admin
      - ELASTIC_PASSWORD=admin
      #- "SERVER_BASEPATH=/usr/share/kibana"
      - "SERVER_HOST=kibana"
    #volumes:
    #  - ./Kibana/bin:/usr/share/kibana/bin
    #  - ./Kibana/config:/usr/share/kibana/config
  logstash:
    image: docker.elastic.co/logstash/logstash:8.10.1
    container_name: logstash
    depends_on:
      - kibana
    volumes:
      - ./Logstash/config:/usr/share/logstash/config
      - ./Logstash/pipeline:/usr/share/logstash/pipeline
